
modLoader="javafml"
loaderVersion="[43,)"
license="MIT"


[[mods]]
modId="creatingspace"
version = "1.19.2_1.8"
displayName="Creating Space"
logoFile = "new_logo.png"
credits='''
Source code:
RealAntEngineer
Icicles
Bream

Translation :
RealAntEngineer -> English and French
PopCorn -> Russian and Ukrainian

Textures :
RealAntEngineer
TheTntExpress
Mr.Sodium
Cosmos
'''
authors="Real Ant Engineer"

description='''
test version for the release
'''

[[dependencies.creatingspace]]
modId="create"
mandatory=true
versionRange="[0.5.1.a,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.creatingspace]]
modId="forge"
mandatory=true
versionRange="[43,)" # Adjust based on your Forge version
ordering="AFTER"
side="BOTH"
